apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: db-book
spec:
  replicas: 1
  serviceName: db-book
  selector:
    matchLabels:
      app: db-book
  template:
    metadata:
      labels:
        app: db-book
    spec:
      containers:
        - name: postgres
          image: {{ .Values.postgres.image | default "postgres:15" }}
          env:
            - name: POSTGRES_USER
              value: "postgres"
            - name: POSTGRES_PASSWORD
              value: "root"
            - name: POSTGRES_DB
              value: "bookdb"
          resources:
            {{- toYaml .Values.postgres.resources | nindent 12 }}
          volumeMounts:
            - name: postgres-storage
              mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
    - metadata:
        name: postgres-storage
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: {{ .Values.postgres.storage | default "1Gi" }}

---
apiVersion: v1
kind: Service
metadata:
  name: db-book  
spec:
  selector:
    app: db-book
  ports:
    - port: 5432
      targetPort: 5432